### PR TITLE
Should check that obj.toJSON is a function before calling it

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rhoggSugarcrm** [comment]
Hey @darrachequesne  any idea when this will be merged? This is blocking us from upgrading our version of Karma-runner because of https://github.com/karma-runner/karma/issues/1686

Thanks!

**Comment by darrachequesne** [comment]
Hi! I have no idea!

ping @rauchg > hi! are you still able to commit in this repository?

Maybe this PR https://github.com/Automattic/has-binary/pull/2 could be merged too before releasing 0.1.7? :heart:

**Comment by darrachequesne** [comment]
(excuse me for the double post) @jderuere could you add a test to prevent any future regression (I edited my comment [here](https://github.com/socketio/socket.io/issues/2284) but you may not have seen it) ?

**Comment by ghost** [comment]
Any possibility to improve the situation?

**Comment by darrachequesne** [comment]
@jderuere hi! I don't know if you've been notified, but your PR has been merged here https://github.com/socketio/has-binary 

And release with has-binary@0.1.7 :metal:

**Comment by ghost** [comment]
Yes I saw it! It's great, thank you

2015-11-19 16:55 GMT-05:00 Damien Arrachequesne notifications@github.com:

**Pull request closed without merging**
